name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: Matchujk/codingChallengeSolutions

        with:
          github-token: ${{ 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 }}
          leetcode-csrf-token: ${{ QjXipbl6OEOMcwfX5eI0YeOTETF4NsVJLS0nwEi6dPRAn4xnowZfRTNNzEnN9sel; }}
          leetcode-session: ${{ eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYXV0aF91c2VyX2lkIjoiODcwNzA5MiIsIl9hdXRoX3VzZXJfYmFja2VuZCI6ImFsbGF1dGguYWNjb3VudC5hdXRoX2JhY2tlbmRzLkF1dGhlbnRpY2F0aW9uQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6ImQ1MmZhNjVmZWNjM2UyZmE0NTAxNWNkYzY3MzE4NzIwZGU3ZmRjYzUiLCJpZCI6ODcwNzA5MiwiZW1haWwiOiJtYXR0aGV3a2VnZXJyZWlzQHlhaG9vLmNvbSIsInVzZXJuYW1lIjoiTWF0Y2h1amsiLCJ1c2VyX3NsdWciOiJNYXRjaHVqayIsImF2YXRhciI6Imh0dHBzOi8vYXNzZXRzLmxlZXRjb2RlLmNvbS91c2Vycy9hdmF0YXJzL2F2YXRhcl8xNjc1NzEyMTAyLnBuZyIsInJlZnJlc2hlZF9hdCI6MTY3NjE4Mzc0MCwiaXAiOiIyNjAxOjI4Mjo4MDAzOmFiMDo3ZGIxOjc1Yjc6YWI0NjpiZmU2IiwiaWRlbnRpdHkiOiJiOWNiZDhkYzEzZjE5ZjllN2ViODU0ZjQ3MmJmYTI3NCIsInNlc3Npb25faWQiOjM1MTAzNjk3fQ.8ktUkDkflzkIo5zPrQryY8EpOOAmCtdYT06Yj }}
          destination-folder: codingChallengeSolution
